name: build
on: [push]
jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: build windows-x86_64
      run: |
        node build.mjs ARCH=windows-x86_64

    - name: build windows-x86
      run: |
        node build.mjs ARCH=windows-x86